# Generated by Django 4.1.5 on 2024-06-02 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='mv_name',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AddField(
            model_name='movie',
            name='mv_poster',
            field=models.CharField(default=' ', max_length=455),
        ),
        migrations.AddField(
            model_name='movie',
            name='mv_year',
            field=models.CharField(default=' ', max_length=255),
        ),
    ]
